// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DateRangeController from "./date_range_controller"
application.register("date-range", DateRangeController)

import FormResetAddTodoController from "./form_reset_add_todo_controller"
application.register("form-reset-add-todo", FormResetAddTodoController)

import FormResetController from "./form_reset_controller"
application.register("form-reset", FormResetController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import SpinerController from "./spiner_controller"
application.register("spiner", SpinerController)
